PlayerHP
PlayerStatsSO PlayerHP._statsSO
float PlayerHP.healCount
PlayerHP PlayerHP.Instance
Referenced by LunchBoxItemSO.OnLVLUp, BloodExperimentQuest.OnQuestStart.
float PlayerHP._currentHP
The _currentHP field.
Referenced by Damage, DamageInPercent, Heal, HealInProcent.
float PlayerHP.MaxHP
The MaxHP field.
Referenced by Damage, DamageInPercent, Heal, HealInProcent, maxHPChanged.
bool PlayerHP.isAlive
The isAlive field.
AudioClip PlayerHP.hitClip
The hitClip field.
Referenced by Damage, DamageInPercent.
Action<float> PlayerHP.Changed
Referenced by Damage, DamageInPercent, Heal, HealInProcent.
Action<float> PlayerHP.MaxHpChanged
Referenced by maxHPChanged.
void PlayerHP.Awake()
void PlayerHP.OnEnable()
void PlayerHP.OnDisable()
void PlayerHP.Death()
void PlayerHP.DamageInPercent(float damageAmmount)
Applies damage.
damageAmmount The damageAmmount.
References _currentHP, Changed, hitClip, AudioManager.Instance, PlayerHitEffect.Instance, SingletonScriptableObject< T >.Instance, MaxHP, AudioManager.PlayHit, AudioManager.ResetMusicPitch, AudioManager.SetMusicPitch, PlayerHitEffect.TakeHit.
Referenced by BloodExperimentQuest.OnQuestStart.
void PlayerHP.Damage(float damageAmmount)
Applies damage.
damageAmmount The damageAmmount.
References _currentHP, Changed, hitClip, AudioManager.Instance, PlayerHitEffect.Instance, SingletonScriptableObject< T >.Instance, MaxHP, AudioManager.PlayHit, AudioManager.ResetMusicPitch, AudioManager.SetMusicPitch, PlayerHitEffect.TakeHit.
void PlayerHP.Heal(float healAmmount)
Applies healing.
healAmmount The healAmmount.
References _currentHP, Changed, AudioManager.Instance, MaxHP, AudioManager.ResetMusicPitch, AudioManager.SetMusicPitch.
Referenced by maxHPChanged, LunchBoxItemSO.OnLVLUp.
void PlayerHP.HealInProcent(float healAmmount)
Applies healing.
healAmmount The healAmmount.
References _currentHP, Changed, AudioManager.Instance, MaxHP, AudioManager.ResetMusicPitch, AudioManager.SetMusicPitch.
void PlayerHP.maxHPChanged(float maxHP)
Executes the maxHPChanged operation.
maxHP The maxHP.
References Heal, MaxHP, MaxHpChanged.