GameStateManager
PauseType
GameStateManager GameStateManager.Instance
Referenced by TransitionQuestStartPanel.HidePanel, LevelUpController.ShowLevelUpOptionsAsync, TransitionQuestStartPanel.ShowTransitionQuestConfirmation, ItemRewardInfo.Skip, TransitionManager.TransitPlayerToLevel, Player.TriggerLoose, Player.TriggerWin.
bool GameStateManager.IsPaused
Referenced by TransitionQuestStartPanel.HidePanel, SetPaused, TogglePause, TransitionManager.TransitPlayerToLevel.
bool GameStateManager.IsInCountdown
Referenced by EndCountdown, SetPaused, StartCountdown.
PauseType GameStateManager.CurrentPauseType
Referenced by TransitionQuestStartPanel.HidePanel, SetPaused.
Action<bool, PauseType> GameStateManager.OnPauseStateChanged
Referenced by SetPaused.
GameObject GameStateManager.MenuCanvas
The MenuCanvas field.
Referenced by TogglePause.
GameObject GameStateManager.SettingsCanvas
The SettingsCanvas field.
Referenced by TogglePause.
void GameStateManager.Awake()
void GameStateManager.Update()
void GameStateManager.TogglePause()
Executes the TogglePause operation.
References AudioManager.Instance, ItemsPanel.Instance, QuestPanel.Instance, IsPaused, MenuCanvas, AudioManager.ResumeMusic, SetPaused, QuestPanel.SetQuestsInfo, SettingsCanvas, CountdownController.StartCountdown.
void GameStateManager.SetPaused(bool paused, PauseType pauseType=PauseType.EscPause)
Sets the Paused.
paused The paused. pauseType The pauseType.
References EnemySpawnManager.ChangeActiveEnemySpawn, CurrentPauseType, AudioManager.DuckMusic, AudioManager.Instance, EnemySpawnManager.Instance, IsInCountdown, IsPaused, OnPauseStateChanged, AudioManager.StopAllSFX, AudioManager.UnduckMusic.
Referenced by ResumeGame, TogglePause.
void GameStateManager.ResumeGame()
Executes the ResumeGame operation.
References AudioManager.Instance, SetPaused, AudioManager.UnduckMusic.
Referenced by TransitionQuestStartPanel.HidePanel, ItemRewardInfo.Skip, TransitionManager.TransitPlayerToLevel.
void GameStateManager.StartCountdown()
Executes the StartCountdown operation.
References IsInCountdown.
void GameStateManager.EndCountdown()
Executes the EndCountdown operation.
References IsInCountdown.
void GameStateManager.PauseGame()
void GameStateManager.PauseForLevelUp()
Referenced by LevelUpController.ShowLevelUpOptionsAsync, TransitionQuestStartPanel.ShowTransitionQuestConfirmation, Player.TriggerLoose, Player.TriggerWin.