ItemRewardInfo
List<GameObject> ItemRewardInfo.ItemsList
Referenced by SetItemsInfo.
ItemType ItemRewardInfo._questGiverType
The _questGiverType field.
Referenced by TransferRandomObjects.
int ItemRewardInfo.numberOfCurrentWeaponList
The numberOfCurrentWeaponList field.
ItemControllerSO ItemRewardInfo._itemControllerSO
The _itemControllerSO field.
Referenced by TransferRandomObjects.
ItemDataSO ItemRewardInfo._universalItem
ItemDataSO ItemRewardInfo._specialisedItem
GameObject ItemRewardInfo._itemRewardCanvas
Sprite ItemRewardInfo.NoItemsSprite
void ItemRewardInfo.OnEnable()
void ItemRewardInfo.OnItemSelected(ItemDataSO item)
void ItemRewardInfo.TransferRandomObjects()
Executes the TransferRandomObjects operation.
References _itemControllerSO, _questGiverType.
Referenced by SetItemsInfo.
void ItemRewardInfo.SetItemsInfo()
Sets the ItemsInfo.
References ItemsList, Skip, TransferRandomObjects.
Referenced by ForceRefreshUI.
void ItemRewardInfo.Skip()
Executes the Skip operation.
References GameStateManager.Instance, GameStateManager.ResumeGame.
Referenced by SetItemsInfo.
void ItemRewardInfo.ForceRefreshUI()
Executes the ForceRefreshUI operation.
References SetItemsInfo.