Generation
GameObject Generation._edgeWall
GameObject Generation._edgeWallCorner
List<GameObject> Generation._tilesVariationList
int Generation._generationHeight
int Generation._generationWidth
List<QuestData> Generation.transitionQuests
List<List<GameObject> > Generation.generation
NavMeshSurface [] Generation.allSurfaces
ItemControllerSO Generation._itemController
Generation Generation.Instance
Referenced by GatherGasQuest.OnQuestStart.
List<QuestData> Generation._availableQuests
Referenced by AddQuestsToTiles.
List<QuestData> Generation._allQuests
int Generation._questsOnMapMin
The _questsOnMapMin field.
Referenced by GenerateMap.
int Generation._questsOnMapMax
The _questsOnMapMax field.
Referenced by GenerateMap.
int Generation._mutationsOnMapMin
The _mutationsOnMapMin field.
Referenced by GenerateMap.
int Generation._mutationsOnMapMax
The _mutationsOnMapMax field.
Referenced by GenerateMap.
void Generation.SpawnGasTanks(int amount)
Spawns GasTanks.
amount The amount.
Referenced by GatherGasQuest.OnQuestStart.
void Generation.InitialiseGenerationList(int _width, int _height)
Executes the InitialiseGenerationList operation.
_width The _width. _height The _height.
References ClearGeneration.
void Generation.AddMutationsChestsToTiles(int _width, int _height, int MutationsMin, int MutationsMax)
Adds MutationsChestsToTiles.
_width The _width. _height The _height. MutationsMin The MutationsMin. MutationsMax The MutationsMax.
References SpawnActivityOnTile._objectsOnTile, SpawnActivityOnTile.SpawnMutationChest.
Referenced by GenerateMap.
void Generation.AddQuestsToTiles(int _width, int _height, int QuestsMin, int QuestsMax)
Adds QuestsToTiles.
_width The _width. _height The _height. QuestsMin The QuestsMin. QuestsMax The QuestsMax.
References _availableQuests, SpawnActivityOnTile._objectsOnTile, SpawnActivityOnTile.SpawnQuestGiverOfType, SpawnActivityOnTile.SpawnTransitionQuest.
Referenced by GenerateMap.
void Generation.GenerateMap(int _width, int _height)
Generates Map.
_width The _width. _height The _height.
References _mutationsOnMapMax, _mutationsOnMapMin, _questsOnMapMax, _questsOnMapMin, AddMutationsChestsToTiles, AddQuestsToTiles, ClearGeneration.
void Generation.BuildNavMesh(NavMeshSurface parentSurface)
Builds NavMesh.
parentSurface The parentSurface.
void Generation.ClearGeneration()
Executes the ClearGeneration operation.
Referenced by GenerateMap, InitialiseGenerationList.
void Generation.Awake()
void Generation.GenerateEdjeWalls()
void Generation.SetupNavMeshSurface()
void Generation.Update()
void Generation.Start()