PlayerStatsSO
string PlayerStatsSO.playerName
The playerName field.
float PlayerStatsSO.DamageMultiplier
The DamageMultiplier field.
Referenced by ChangeDamageMultiplier, UpdateAllPlayerStats.
float PlayerStatsSO.MagicDamageMultiplier
The MagicDamageMultiplier field.
Referenced by ChangeMagicDamageMultiplier, UpdateAllPlayerStats.
float PlayerStatsSO.TechnoDamageMultiplier
The TechnoDamageMultiplier field.
Referenced by ChangeTechnoDamageMultiplier, UpdateAllPlayerStats.
float PlayerStatsSO.CooldownReduction
The CooldownReduction field.
Referenced by ChangeCooldownReduction, UpdateAllPlayerStats.
float PlayerStatsSO.AreaMultiplier
The AreaMultiplier field.
Referenced by ChangeAreaMultiplier, UpdateAllPlayerStats.
float PlayerStatsSO.MaxHP
The MaxHP field.
Referenced by ChangeMaxHp, UpdateAllPlayerStats.
float PlayerStatsSO.MoveSpeed
The MoveSpeed field.
Referenced by ChangeMoveSpeed, UpdateAllPlayerStats.
float PlayerStatsSO.SpeedMultiplier
The SpeedMultiplier field.
Referenced by ChangeSpeedMultiplier, UpdateAllPlayerStats.
long PlayerStatsSO.Money
The Money field.
Referenced by ChangeMoney, InitializationManager.ResetPlayerStats, UpdateAllPlayerStats.
long PlayerStatsSO.MaxMoney
The MaxMoney field.
Referenced by ChangeMoney.
float PlayerStatsSO.Reputation
The Reputation field.
Referenced by ChangeReputation, UpdateAllPlayerStats.
int PlayerStatsSO.maxEXP
The maxEXP field.
Referenced by ExpandEXP.
int PlayerStatsSO.maxLevel
The maxLevel field.
bool PlayerStatsSO.invincibility
The invincibility field.
float PlayerStatsSO.CurrentKills
The CurrentKills field.
Referenced by ChangeKills, UpdateAllPlayerStats.
bool PlayerStatsSO._reputationTecnoEffect
The _reputationTecnoEffect field.
Referenced by ChangeReputation.
bool PlayerStatsSO._reputationMagicEffect
The _reputationMagicEffect field.
Referenced by ChangeReputation.
Action<float> PlayerStatsSO._damageMultiplierChanged
Referenced by ChangeDamageMultiplier, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._magicDamageMultiplierChanged
Referenced by ChangeMagicDamageMultiplier, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._technoDamageMultiplierChanged
Referenced by ChangeTechnoDamageMultiplier, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._cooldownReductionChanged
Referenced by ChangeCooldownReduction, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._areaMultiplierChanged
Referenced by ChangeAreaMultiplier, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._speedMultiplierChanged
Referenced by ChangeSpeedMultiplier, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._moneyChanged
Referenced by ChangeMoney, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._reputationChanged
Referenced by ChangeReputation, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._moveSpeedChanged
Referenced by ChangeMoveSpeed, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._maxHpChanged
Referenced by ChangeMaxHp, UpdateAllPlayerStats.
Action<float> PlayerStatsSO._killsChanged
Referenced by ChangeKills, UpdateAllPlayerStats.
void PlayerStatsSO.Awake()
void PlayerStatsSO.ExpandEXP()
Executes the ExpandEXP operation.
References maxEXP.
void PlayerStatsSO.UpdateAllPlayerStats()
Updates AllPlayerStats.
References _areaMultiplierChanged, _cooldownReductionChanged, _damageMultiplierChanged, _killsChanged, _magicDamageMultiplierChanged, _maxHpChanged, _moneyChanged, _moveSpeedChanged, _reputationChanged, _speedMultiplierChanged, _technoDamageMultiplierChanged, AreaMultiplier, CooldownReduction, CurrentKills, DamageMultiplier, MagicDamageMultiplier, MaxHP, Money, MoveSpeed, Reputation, SpeedMultiplier, TechnoDamageMultiplier.
Referenced by InitializationManager.ResetPlayerStats.
void PlayerStatsSO.ChangeDamageMultiplier(float value)
Executes the ChangeDamageMultiplier operation.
value The value.
References _damageMultiplierChanged, DamageMultiplier.
Referenced by ChangeReputation.
void PlayerStatsSO.ChangeMagicDamageMultiplier(float value)
Executes the ChangeMagicDamageMultiplier operation.
value The value.
References _magicDamageMultiplierChanged, MagicDamageMultiplier.
void PlayerStatsSO.ChangeTechnoDamageMultiplier(float value)
Executes the ChangeTechnoDamageMultiplier operation.
value The value.
References _technoDamageMultiplierChanged, TechnoDamageMultiplier.
void PlayerStatsSO.ChangeMaxHp(float value)
Executes the ChangeMaxHp operation.
value The value.
References _maxHpChanged, MaxHP.
void PlayerStatsSO.ChangeCooldownReduction(float value)
Executes the ChangeCooldownReduction operation.
value The value.
References _cooldownReductionChanged, CooldownReduction.
Referenced by ChangeReputation.
void PlayerStatsSO.ChangeAreaMultiplier(float value)
Executes the ChangeAreaMultiplier operation.
value The value.
References _areaMultiplierChanged, AreaMultiplier.
void PlayerStatsSO.ChangeSpeedMultiplier(float value)
Executes the ChangeSpeedMultiplier operation.
value The value.
References _speedMultiplierChanged, SpeedMultiplier.
void PlayerStatsSO.ChangeMoney(long value)
Executes the ChangeMoney operation.
value The value.
References _moneyChanged, MaxMoney, Money.
void PlayerStatsSO.ChangeReputation(float value)
Executes the ChangeReputation operation.
value The value.
References _reputationChanged, _reputationMagicEffect, _reputationTecnoEffect, ChangeCooldownReduction, ChangeDamageMultiplier, UniversalNotification.Instance, Reputation, UniversalNotification.ShowNotification.
void PlayerStatsSO.ChangeMoveSpeed(float value)
Executes the ChangeMoveSpeed operation.
value The value.
References _moveSpeedChanged, MoveSpeed.
void PlayerStatsSO.ChangeKills(long value)
Executes the ChangeKills operation.
value The value.
References _killsChanged, CurrentKills.