QuestManager
QuestManager QuestManager.Instance
Referenced by GasTank.Interact, QuestGiver.Interact, BloodExperimentQuest.OnQuestCancel, EnemyKillerQuest.OnQuestCancel, GatherGasQuest.OnQuestCancel, MagicBlizzardQuest.OnQuestCancel, QuestData.OnQuestCancel, BloodExperimentQuest.OnQuestFinish, EnemyKillerQuest.OnQuestFinish, GatherGasQuest.OnQuestFinish, MagicBlizzardQuest.OnQuestFinish, BloodExperimentQuest.OnQuestStart, EnemyKillerQuest.OnQuestStart, GatherGasQuest.OnQuestStart, MagicBlizzardQuest.OnQuestStart, QuestData.OnQuestTurnedIn, TransitionManager.TransitPlayerToLevel.
List<QuestData> QuestManager.completedQuests
Referenced by CancelQuest, TransitionManager.TransitPlayerToLevel, TurnInQuest, UnregisterQuest.
List<QuestData> QuestManager.activeQuests
Referenced by BlizzardShieldProgressForOne, CancelQuest, GasTankGathered, OnEnemyKilled, RegisterQuest, TransitionManager.TransitPlayerToLevel, UnregisterQuest.
AudioClip QuestManager.QuestClip
The QuestClip field.
Referenced by QuestGiver.Interact.
List<QuestData> QuestManager.canceledQuests
Action QuestManager._onQuestRegistered
Referenced by RegisterQuest.
Action QuestManager._onQuestFinished
Referenced by UnregisterQuest.
Action QuestManager._onQuestProgressUpdated
Referenced by OnQuestProgressUpdated.
Action QuestManager._onQuestCanceled
Referenced by CancelQuest.
Action QuestManager._onQuestTurnedIn
Referenced by TurnInQuest.
void QuestManager.Awake()
void QuestManager.RegisterQuest(QuestData quest)
Executes the RegisterQuest operation.
quest The quest.
References _onQuestRegistered, activeQuests, QuestNotification.Instance, QuestSO.QuestName, QuestNotification.ShowQuestAccepted.
Referenced by BloodExperimentQuest.OnQuestStart, EnemyKillerQuest.OnQuestStart, GatherGasQuest.OnQuestStart, MagicBlizzardQuest.OnQuestStart.
void QuestManager.UnregisterQuest(QuestData quest)
Executes the UnregisterQuest operation.
quest The quest.
References _onQuestFinished, activeQuests, completedQuests, QuestNotification.Instance, QuestSO.QuestName, QuestNotification.ShowQuestCompleted.
Referenced by BloodExperimentQuest.OnQuestFinish, EnemyKillerQuest.OnQuestFinish, GatherGasQuest.OnQuestFinish, MagicBlizzardQuest.OnQuestFinish.
void QuestManager.TurnInQuest(QuestData quest)
Executes the TurnInQuest operation.
quest The quest.
References _onQuestTurnedIn, completedQuests, QuestNotification.Instance, QuestSO.QuestName, QuestNotification.ShowQuestTurnedIn.
Referenced by QuestGiver.Interact, QuestData.OnQuestTurnedIn.
void QuestManager.CancelQuest(QuestData quest)
Executes the CancelQuest operation.
quest The quest.
References _onQuestCanceled, activeQuests, completedQuests, QuestNotification.Instance, QuestSO.QuestName, QuestNotification.ShowQuestFailed.
Referenced by BloodExperimentQuest.OnQuestCancel, EnemyKillerQuest.OnQuestCancel, GatherGasQuest.OnQuestCancel, MagicBlizzardQuest.OnQuestCancel, QuestData.OnQuestCancel, TransitionManager.TransitPlayerToLevel.
void QuestManager.OnQuestProgressUpdated(QuestData quest)
Event handler for OnQuestProgressUpdated.
quest The quest.
References _onQuestProgressUpdated, QuestNotification.Instance, QuestData.progress, QuestSO.QuestName, QuestNotification.ShowQuestProgress.
Referenced by BlizzardShieldProgressForOne, GasTankGathered, OnEnemyKilled.
void QuestManager.OnEnemyKilled(int enemyType=0)
Event handler for OnEnemyKilled.
enemyType The enemyType.
References QuestData.active, activeQuests, OnQuestProgressUpdated.
void QuestManager.GasTankGathered()
Executes the GasTankGathered operation.
References QuestData.active, activeQuests, OnQuestProgressUpdated.
Referenced by GasTank.Interact.
void QuestManager.BlizzardShieldProgressForOne()
Executes the BlizzardShieldProgressForOne operation.
References QuestData.active, activeQuests, OnQuestProgressUpdated.