ItemDataSO
string ItemDataSO.itemTitle
The itemTitle field.
string ItemDataSO.description
The description field.
Sprite ItemDataSO.icon
The icon field.
bool ItemDataSO.isActiveItem
The isActiveItem field.
Referenced by ItemControllerSO.DistributeItem.
bool ItemDataSO.isActive
The isActive field.
Referenced by OnPick.
ItemType ItemDataSO.itemType
The itemType field.
Referenced by ItemControllerSO.DistributeItem.
bool ItemDataSO.HasOnEnemyDeathEvent
The HasOnEnemyDeathEvent field.
Referenced by ItemControllerSO.DistributeItem.
bool ItemDataSO.HasOnSceneChangeEvent
The HasOnSceneChangeEvent field.
Referenced by ItemControllerSO.DistributeItem.
bool ItemDataSO.HasOnDamageGiveEvent
The HasOnDamageGiveEvent field.
Referenced by ItemControllerSO.DistributeItem.
bool ItemDataSO.HasOnLVLUpEvent
The HasOnLVLUpEvent field.
Referenced by ItemControllerSO.DistributeItem.
float ItemDataSO.ReputationAmount
The ReputationAmount field.
Referenced by OnPick.
ItemControllerSO ItemDataSO.ItemController
The ItemController field.
virtual void ItemDataSO.OnPick()
References ItemsPanel.Instance, SingletonScriptableObject< T >.Instance, isActive, ReputationAmount, ItemsPanel.SetItemsInfo.
virtual void ItemDataSO.OnEnemyDeath(GameObject enemy)
Referenced by ItemControllerSO.ActivateOnEnemyDeathEvent.
virtual void ItemDataSO.OnSceneChange()
Referenced by ItemControllerSO.ActivateOnSceneChangeEvent.
virtual void ItemDataSO.OnDamageGive()
Referenced by ItemControllerSO.ActivateOnDamageGiveEvent.
virtual void ItemDataSO.OnLVLUp()
Referenced by ItemControllerSO.ActivateOnLVLUpEvent.