UIAnimator
AnimationType
AnimationType UIAnimator.animationType
The animationType field.
Referenced by AnimateIn, AnimateOut, PlayAnimation, PlayAttentionBounce, PlayQuickScaleUp, PlaySmoothFade.
float UIAnimator.duration
The duration field.
Referenced by AnimateInCustom, AnimateOut, PlayAttentionBounce, PlayQuickScaleUp, PlaySmoothFade.
float UIAnimator.delay
The delay field.
Referenced by AnimateInCustom, AnimateOut.
Ease UIAnimator.easeType
The easeType field.
Referenced by AnimateInCustom, AnimateOut, PlaySmoothFade.
float UIAnimator.strength
The strength field.
Referenced by PlayAttentionBounce, PlayQuickScaleUp.
Vector3 UIAnimator.slideOffset
The slideOffset field.
bool UIAnimator.animateOnEnable
The animateOnEnable field.
bool UIAnimator.animateOnStart
The animateOnStart field.
bool UIAnimator.resetOnDisable
The resetOnDisable field.
bool UIAnimator.ignoreTimescale
The ignoreTimescale field.
Referenced by AnimateOut.
Vector3 UIAnimator.originalPosition
Vector3 UIAnimator.originalScale
CanvasGroup UIAnimator.canvasGroup
Tween UIAnimator.currentTween
void UIAnimator.Start()
void UIAnimator.OnEnable()
void UIAnimator.OnDisable()
void UIAnimator.ResetToOriginal()
void UIAnimator.AnimateScaleUp()
void UIAnimator.AnimateSlide(Vector3 direction)
void UIAnimator.AnimateFadeIn()
void UIAnimator.AnimateBounce()
void UIAnimator.AnimateFlip()
void UIAnimator.AnimatePulse()
void UIAnimator.AnimateShake()
void UIAnimator.AnimateIn()
Executes the AnimateIn operation.
References animationType.
Referenced by AnimateInCustom, PlayAnimation, PlayAttentionBounce, PlayQuickScaleUp, PlaySmoothFade.
void UIAnimator.AnimateOut()
Executes the AnimateOut operation.
References animationType, delay, duration, easeType, ignoreTimescale.
void UIAnimator.AnimateInCustom(float customDuration, float customDelay, Ease customEase)
Executes the AnimateInCustom operation.
customDuration The customDuration. customDelay The customDelay. customEase The customEase.
References AnimateIn, delay, duration, easeType.
void UIAnimator.PlayAnimation(AnimationType type)
Plays animation or sound.
type The type.
References AnimateIn, animationType.
void UIAnimator.StopAnimation()
Stops animation or sound.
void UIAnimator.PauseAnimation(bool pause)
Executes the PauseAnimation operation.
pause The pause.
void UIAnimator.PlayScaleUp()
void UIAnimator.PlaySlideFromLeft()
void UIAnimator.PlaySlideFromBottom()
void UIAnimator.PlayFadeIn()
void UIAnimator.PlayBounce()
void UIAnimator.PlayQuickScaleUp()
Plays animation or sound.
References AnimateIn, animationType, duration, strength.
void UIAnimator.PlaySmoothFade()
Plays animation or sound.
References AnimateIn, animationType, duration, easeType.
void UIAnimator.PlayAttentionBounce()
Plays animation or sound.
References AnimateIn, animationType, duration, strength.