SpawnActivityOnTile
GameObject SpawnActivityOnTile._questGiver
The _questGiver field.
Referenced by SpawnQuestGiverOfType, SpawnTransitionQuest.
GameObject SpawnActivityOnTile._mutationChest
The _mutationChest field.
Referenced by SpawnMutationChest.
GameObject SpawnActivityOnTile._gasTank
The _gasTank field.
Referenced by SpawnGasTank.
List<ActivityOnTileType> SpawnActivityOnTile._objectsOnTile
Referenced by Generation.AddMutationsChestsToTiles, Generation.AddQuestsToTiles.
Transform SpawnActivityOnTile._questGiverSpawnPoint
Transform SpawnActivityOnTile._mutationChestSpawnPoint
Transform SpawnActivityOnTile._gasTankSpawnPoint
void SpawnActivityOnTile.SpawnGasTank()
Spawns GasTank.
References _gasTank.
void SpawnActivityOnTile.SpawnQuestGiverOfType(QuestData Quest, ItemType QuestType)
Spawns QuestGiverOfType.
Quest The Quest. QuestType The QuestType.
References _questGiver, Quest.
Referenced by Generation.AddQuestsToTiles.
void SpawnActivityOnTile.SpawnMutationChest()
Spawns MutationChest.
References _mutationChest.
Referenced by Generation.AddMutationsChestsToTiles.
void SpawnActivityOnTile.SpawnTransitionQuest(QuestData Quest)
Spawns TransitionQuest.
Quest The Quest.
References _questGiver, Quest.
Referenced by Generation.AddQuestsToTiles.