AudioManager
AudioManager AudioManager.Instance
Referenced by PlayerHP.Damage, PlayerHP.DamageInPercent, GetMusicVolume, PlayerHP.Heal, PlayerHP.HealInProcent, Chest.Interact, QuestGiver.Interact, GameStateManager.ResumeGame, GameStateManager.SetPaused, GameStateManager.TogglePause, LevelUpController.UiClickSound, UIClickSound.UiClickSound.
AudioSource AudioManager.sfxSource
The sfxSource field.
Referenced by PlaySFX.
AudioSource AudioManager.musicSource
The musicSource field.
Referenced by DuckMusic, PauseMusic, PlayMusic, ResumeMusic, SetMusicPitch, StopMusic, UnduckMusic.
AudioSource AudioManager.walkSource
The walkSource field.
Referenced by PlayWalk, StopWalk.
AudioSource AudioManager.hitSource
The hitSource field.
Referenced by PlayHit, StopHit.
AudioSource AudioManager.shootSource
The shootSource field.
Referenced by PlayShoot, StopShoot.
AudioSource AudioManager.openChestSource
The openChestSource field.
Referenced by PlayOpenChest.
AudioSource AudioManager.QuestSource
The QuestSource field.
Referenced by PlayQuest.
AudioSource AudioManager.levelUpSource
The levelUpSource field.
Referenced by PlayLevelUp.
AudioSource AudioManager.uiClickSource
The uiClickSource field.
Referenced by PlayClick.
AudioMixer AudioManager.audioMixer
The audioMixer field.
float AudioManager.masterVolume
The masterVolume field.
Referenced by GetMasterVolume, SetMasterVolume, ToggleMute.
float AudioManager.sfxVolume
The sfxVolume field.
Referenced by GetSFXVolume, SetSFXVolume, ToggleSFXMute.
float AudioManager.musicVolume
The musicVolume field.
Referenced by GetMusicVolume, SetMusicVolume, ToggleMusicMute.
const string AudioManager.MASTER_VOL_KEY
const string AudioManager.SFX_VOL_KEY
const string AudioManager.MUSIC_VOL_KEY
bool AudioManager.isMusicPaused
Dictionary<AudioSource, float> AudioManager.sourceBaseVolumes
void AudioManager.Awake()
void AudioManager.ConfigureAudioSources()
IEnumerator AudioManager.DuckMusicCoroutine(float targetDuckAmount, float duration)
IEnumerator AudioManager.UnduckMusicCoroutine(float duration)
IEnumerator AudioManager.ChangePitchCoroutine(float targetPitch, float duration)
void AudioManager.UpdateAllVolumes()
void AudioManager.UpdateMixerVolumes()
void AudioManager.SaveVolumeSettings()
void AudioManager.LoadVolumeSettings()
void AudioManager.OnDestroy()
void AudioManager.PlaySFX(AudioClip clip, float volumeScale=1f)
Plays animation or sound.
clip The clip. volumeScale The volumeScale.
References sfxSource.
void AudioManager.PlaySFXAtPosition(AudioClip clip, Vector3 position, float volumeScale=1f)
Plays animation or sound.
clip The clip. position The position. volumeScale The volumeScale.
void AudioManager.PlayWalk(AudioClip clip, float volumeScale=0.7f)
Plays animation or sound.
clip The clip. volumeScale The volumeScale.
References walkSource.
void AudioManager.StopAllSFX()
Stops animation or sound.
References StopHit, StopShoot, StopWalk.
Referenced by GameStateManager.SetPaused.
void AudioManager.StopWalk()
Stops animation or sound.
References walkSource.
Referenced by StopAllSFX.
void AudioManager.PlayHit(AudioClip clip, float volumeScale=1f)
Plays animation or sound.
clip The clip. volumeScale The volumeScale.
References hitSource.
Referenced by PlayerHP.Damage, PlayerHP.DamageInPercent.
void AudioManager.StopHit()
Stops animation or sound.
References hitSource.
Referenced by StopAllSFX.
void AudioManager.PlayShoot(AudioClip clip, float volumeScale=1f)
Plays animation or sound.
clip The clip. volumeScale The volumeScale.
References shootSource.
void AudioManager.StopShoot()
Stops animation or sound.
References shootSource.
Referenced by StopAllSFX.
void AudioManager.PlayOpenChest(AudioClip clip, float volumeScale=1f)
Plays animation or sound.
clip The clip. volumeScale The volumeScale.
References openChestSource.
Referenced by Chest.Interact.
void AudioManager.PlayQuest(AudioClip clip, float volumeScale=1f)
Plays animation or sound.
clip The clip. volumeScale The volumeScale.
References QuestSource.
Referenced by QuestGiver.Interact.
void AudioManager.PlayLevelUp(AudioClip clip, float volumeScale=1f)
Plays animation or sound.
clip The clip. volumeScale The volumeScale.
References levelUpSource.
void AudioManager.PlayClick(AudioClip clip, float volumeScale=1f)
Plays animation or sound.
clip The clip. volumeScale The volumeScale.
References uiClickSource.
Referenced by LevelUpController.UiClickSound, UIClickSound.UiClickSound.
void AudioManager.PauseMusic()
Executes the PauseMusic operation.
References musicSource.
void AudioManager.ResumeMusic()
Executes the ResumeMusic operation.
References musicSource.
Referenced by GameStateManager.TogglePause.
void AudioManager.StopMusic()
Stops animation or sound.
References musicSource.
void AudioManager.PlayMusic(AudioClip clip, bool loop=true, float volumeScale=1f)
Plays animation or sound.
clip The clip. loop The loop. volumeScale The volumeScale.
References musicSource.
void AudioManager.DuckMusic(float duckAmount=0.5f, float fadeDuration=0.5f)
Executes the DuckMusic operation.
duckAmount The duckAmount. fadeDuration The fadeDuration.
References musicSource.
Referenced by GameStateManager.SetPaused.
void AudioManager.UnduckMusic(float fadeDuration=0.5f)
Executes the UnduckMusic operation.
fadeDuration The fadeDuration.
References musicSource.
Referenced by GameStateManager.ResumeGame, GameStateManager.SetPaused.
void AudioManager.SetMusicPitch(float pitch, float transitionDuration=1f)
Sets the MusicPitch.
pitch The pitch. transitionDuration The transitionDuration.
References musicSource.
Referenced by PlayerHP.Damage, PlayerHP.DamageInPercent, PlayerHP.Heal, PlayerHP.HealInProcent, ResetMusicPitch.
void AudioManager.ResetMusicPitch(float transitionDuration=1f)
Resets MusicPitch.
transitionDuration The transitionDuration.
References SetMusicPitch.
Referenced by PlayerHP.Damage, PlayerHP.DamageInPercent, PlayerHP.Heal, PlayerHP.HealInProcent.
void AudioManager.SetMasterVolume(float volume)
Sets the MasterVolume.
volume The volume.
References masterVolume.
Referenced by SetMasterVolumeMixer, ToggleMute.
void AudioManager.SetSFXVolume(float volume)
Sets the SFXVolume.
volume The volume.
References sfxVolume.
Referenced by SetSFXVolumeMixer, ToggleSFXMute.
void AudioManager.SetMusicVolume(float volume)
Sets the MusicVolume.
volume The volume.
References musicVolume.
Referenced by SetMusicVolumeMixer, ToggleMusicMute.
void AudioManager.SetMasterVolumeMixer(float volume)
Sets the MasterVolumeMixer.
volume The volume.
References SetMasterVolume.
void AudioManager.SetSFXVolumeMixer(float volume)
Sets the SFXVolumeMixer.
volume The volume.
References SetSFXVolume.
void AudioManager.SetMusicVolumeMixer(float volume)
Sets the MusicVolumeMixer.
volume The volume.
References SetMusicVolume.
void AudioManager.ToggleMute()
Executes the ToggleMute operation.
References masterVolume, SetMasterVolume.
void AudioManager.ToggleMusicMute()
Executes the ToggleMusicMute operation.
References musicVolume, SetMusicVolume.
void AudioManager.ToggleSFXMute()
Executes the ToggleSFXMute operation.
References SetSFXVolume, sfxVolume.
float AudioManager.GetMasterVolume()
References masterVolume.
float AudioManager.GetSFXVolume()
References sfxVolume.
float AudioManager.GetMusicVolume()
References Instance, musicVolume.