EnemySpawner
EnemySpawner EnemySpawner.Instance
Camera EnemySpawner._spawnCamera
The _spawnCamera field.
Referenced by GetRandomEdgePoint.
Transform EnemySpawner._playerTransform
void EnemySpawner.Awake()
void EnemySpawner.Start()
Vector3 EnemySpawner.GetRandomEdgePoint()
Gets the RandomEdgePoint.
The result as Vector3.
References _spawnCamera.
Referenced by SpawnFastMeleeEnemy, SpawnSmallMeleeEnemy, SpawnSmallRangedEnemy, SpawnStrongMeleeEnemy.
void EnemySpawner.SpawnSmallMeleeEnemy(Vector3 position)
Spawns SmallMeleeEnemy.
position The position.
References EnemyPoolList._smallMeleeEnemy, EnemyPool.GetEnemy, EnemyPoolList.instance.
void EnemySpawner.SpawnSmallRangedEnemy(Vector3 position)
Spawns SmallRangedEnemy.
position The position.
References EnemyPoolList._smallRangedEnemy, EnemyPool.GetEnemy, EnemyPoolList.instance.
void EnemySpawner.SpawnFastMeleeEnemy(Vector3 position)
Spawns FastMeleeEnemy.
position The position.
References EnemyPoolList._fastMeleeEnemy, EnemyPool.GetEnemy, EnemyPoolList.instance.
void EnemySpawner.SpawnStrongMeleeEnemy(Vector3 position)
Spawns StrongMeleeEnemy.
position The position.
References EnemyPoolList._strongMeleeEnemy, EnemyPool.GetEnemy, EnemyPoolList.instance.
void EnemySpawner.SpawnSmallMeleeEnemy()
Spawns SmallMeleeEnemy.
References GetRandomEdgePoint, SpawnSmallMeleeEnemy.
Referenced by SpawnSmallMeleeEnemy.
void EnemySpawner.SpawnSmallRangedEnemy()
Spawns SmallRangedEnemy.
References GetRandomEdgePoint, SpawnSmallRangedEnemy.
Referenced by SpawnSmallRangedEnemy.
void EnemySpawner.SpawnFastMeleeEnemy()
Spawns FastMeleeEnemy.
References GetRandomEdgePoint, SpawnFastMeleeEnemy.
Referenced by SpawnFastMeleeEnemy.
void EnemySpawner.SpawnStrongMeleeEnemy()
Spawns StrongMeleeEnemy.
References GetRandomEdgePoint, SpawnStrongMeleeEnemy.
Referenced by SpawnStrongMeleeEnemy.