QuestNotification
QuestNotification QuestNotification.Instance
Referenced by QuestManager.CancelQuest, QuestManager.OnQuestProgressUpdated, QuestManager.RegisterQuest, QuestManager.TurnInQuest, QuestManager.UnregisterQuest.
RectTransform QuestNotification.notificationPanel
Image QuestNotification.backgroundImage
TextMeshProUGUI QuestNotification.titleText
TextMeshProUGUI QuestNotification.descriptionText
Image QuestNotification.iconImage
float QuestNotification.slideDuration
float QuestNotification.hideDelay
Color QuestNotification.acceptedColor
Color QuestNotification.completedColor
Color QuestNotification.turnedInColor
Color QuestNotification.failedColor
Sprite QuestNotification.acceptedIcon
Sprite QuestNotification.completedIcon
Sprite QuestNotification.turnedInIcon
Sprite QuestNotification.failedIcon
Vector2 QuestNotification.hiddenPosition
Vector2 QuestNotification.shownPosition
Sequence QuestNotification.currentAnimation
void QuestNotification.Awake()
void QuestNotification.ShowNotification(string title, string description, Color color, Sprite icon)
void QuestNotification.OnDestroy()
void QuestNotification.ShowQuestAccepted(string questName)
Shows UI element.
questName The questName.
Referenced by QuestManager.RegisterQuest.
void QuestNotification.ShowQuestCompleted(string questName)
Shows UI element.
questName The questName.
Referenced by QuestManager.UnregisterQuest.
void QuestNotification.ShowQuestTurnedIn(string questName)
Shows UI element.
questName The questName.
Referenced by QuestManager.TurnInQuest.
void QuestNotification.ShowQuestFailed(string questName)
Shows UI element.
questName The questName.
Referenced by QuestManager.CancelQuest.
void QuestNotification.ShowQuestProgress(string questName, int progress)
Shows UI element.
questName The questName. progress The progress.
Referenced by QuestManager.OnQuestProgressUpdated.
void QuestNotification.HideNotification()
Hides UI element.