LvlUpWeaponItemsInfo
List<Weapon> LvlUpWeaponItemsInfo._currentWeaponList
Referenced by SetItemsInfo, TransferRandomObjects.
List<GameObject> LvlUpWeaponItemsInfo.ItemsList
Referenced by SetItemsInfo.
List<Weapon> LvlUpWeaponItemsInfo.allWeaponList
Referenced by SetWeaponList.
int LvlUpWeaponItemsInfo.numberOfCurrentWeaponList
The numberOfCurrentWeaponList field.
Referenced by TransferRandomObjects.
LevelUpController LvlUpWeaponItemsInfo.levelUpController
The levelUpController field.
AudioClip LvlUpWeaponItemsInfo.lvlUpClip
The lvlUpClip field.
bool LvlUpWeaponItemsInfo.AllWeaponsGathered
The AllWeaponsGathered field.
List<Weapon> LvlUpWeaponItemsInfo.weaponList
void LvlUpWeaponItemsInfo.Start()
void LvlUpWeaponItemsInfo.OnEnable()
void LvlUpWeaponItemsInfo.OnDisable()
void LvlUpWeaponItemsInfo.SubscribeToAllWeapons()
void LvlUpWeaponItemsInfo.UnsubscribeFromAllWeapons()
void LvlUpWeaponItemsInfo.OnWeaponAvailableChanged()
void LvlUpWeaponItemsInfo.OnWeaponLevelUp(Weapon weapon)
void LvlUpWeaponItemsInfo.ShuffleWeaponList()
void LvlUpWeaponItemsInfo.OnItemSelected(int itemIndex)
void LvlUpWeaponItemsInfo.SetWeaponList()
Sets the WeaponList.
References allWeaponList.
Referenced by SetItemsInfo.
void LvlUpWeaponItemsInfo.TransferRandomObjects()
Executes the TransferRandomObjects operation.
References _currentWeaponList, numberOfCurrentWeaponList.
Referenced by SetItemsInfo.
void LvlUpWeaponItemsInfo.SetItemsInfo()
Sets the ItemsInfo.
References _currentWeaponList, WeaponsPanel.Instance, ItemsList, SetWeaponList, WeaponsPanel.SetWeaponsInfo, TransferRandomObjects.
Referenced by ForceRefreshUI.
void LvlUpWeaponItemsInfo.ForceRefreshUI()
Executes the ForceRefreshUI operation.
References SetItemsInfo.