Weapon
PlayerStatsSO Weapon.playerStats
The playerStats field.
Referenced by CalculateCooldown, CalculateDamage, CalculateDamage, DamageFieldTrigger.SubscribeToPlayerStats, Laser.SubscribeToPlayerStats, MagicStaff.SubscribeToPlayerStats, SubscribeToPlayerStats, DamageFieldTrigger.UnsubscribeFromPlayerStats, Laser.UnsubscribeFromPlayerStats, MagicStaff.UnsubscribeFromPlayerStats, UnsubscribeFromPlayerStats.
WeaponDataSO Weapon.weaponData
The weaponData field.
Referenced by AddLevel, CalculateCooldown, CalculateDamage, CalculateDamage, CanLevelUp, DebugWeaponStats, GetItemDescription, BulletShooter.GetTextTitleInfo, DamageFieldTrigger.GetTextTitleInfo, Laser.GetTextTitleInfo, MagicStaff.GetTextTitleInfo, GetUpgradeDescriptionForNextLevel, BulletShooter.InitializeWeapon, DamageFieldTrigger.InitializeWeapon, Laser.InitializeWeapon, MagicStaff.InitializeWeapon, InitializeWeapon.
int Weapon.currentLevel
The currentLevel field.
Referenced by AddLevel, CalculateCooldown, CalculateDamage, CalculateDamage, CanLevelUp, GetUpgradeDescriptionForNextLevel, ReduceLevel.
bool Weapon.IsAvailable
The IsAvailable field.
Referenced by SetAvailable.
Action Weapon.AvailableChanged
The AvailableChanged field.
Referenced by SetAvailable.
System.Action<Weapon> Weapon.OnLevelUp
Referenced by AddLevel.
float Weapon.currentDamage
Referenced by Laser.CalculateDamage, MagicStaff.CalculateDamage, CalculateDamage, CalculateDamage, GetDamage.
float Weapon.currentCooldown
Referenced by CalculateCooldown, GetCooldown.
WeaponDataSO Weapon.Data
The Data field.
Referenced by WeaponSaveManager.ApplySavedStateToWeapon.
PlayerStatsSO Weapon.PlayerStatsData
The PlayerStatsData field.
int Weapon.CurrentLevel
The CurrentLevel field.
Referenced by WeaponSaveManager.ApplySavedStateToWeapon.
bool Weapon.IsMaxLevel
The IsMaxLevel field.
void Weapon.Update()
void Weapon.OnEnable()
void Weapon.OnDisable()
void Weapon.OnCooldownReductionChanged(float cooldownReduction)
void Weapon.OnDamageMultiplierChanged(float damageMultiplier)
void Weapon.UpdatePlayerStats()
virtual void Weapon.Awake()
References InitializeWeapon.
virtual void Weapon.InitializeWeapon()
References weaponData.
Referenced by Awake.
virtual void Weapon.SubscribeToPlayerStats()
References playerStats.
virtual void Weapon.UnsubscribeFromPlayerStats()
References playerStats.
virtual void Weapon.CalculateAllStats()
References CalculateCooldown, CalculateDamage.
Referenced by AddLevel, ReduceLevel.
virtual void Weapon.CalculateDamage()
References currentDamage, currentLevel, playerStats, weaponData.
Referenced by CalculateAllStats.
virtual void Weapon.CalculateDamage(float DamageMultiplier)
References currentDamage, currentLevel, playerStats, weaponData.
virtual void Weapon.CalculateCooldown()
References currentCooldown, currentLevel, playerStats, weaponData.
Referenced by CalculateAllStats.
virtual bool Weapon.CanLevelUp()
References currentLevel, weaponData.
Referenced by AddLevel, GetUpgradeDescriptionForNextLevel.
virtual void Weapon.AddLevel(int levels=1)
References CalculateAllStats, CanLevelUp, currentLevel, SingletonScriptableObject< T >.Instance, OnLevelUp, weaponData.
Referenced by WeaponSaveManager.ApplySavedStateToWeapon, TestAddLevel.
virtual void Weapon.ReduceLevel(int levels=1)
References CalculateAllStats, currentLevel.
string Weapon.GetTextTitleInfo()
string Weapon.GetTextDescriptionInfo()
virtual string Weapon.GetUpgradeDescriptionForNextLevel()
References CanLevelUp, currentLevel, weaponData.
Referenced by BulletShooter.GetTextDescriptionInfo, DamageFieldTrigger.GetTextDescriptionInfo, Laser.GetTextDescriptionInfo, MagicStaff.GetTextDescriptionInfo.
virtual string Weapon.GetItemDescription()
References weaponData.
virtual float Weapon.GetCooldown()
References currentCooldown.
virtual float Weapon.GetDamage()
References currentDamage.
virtual float Weapon.GetArea()
virtual float Weapon.GetProjectileSpeed()
virtual float Weapon.GetLifetime()
virtual int Weapon.GetDamageType()
virtual string Weapon.GetWeaponStats()
void Weapon.SetAvailable(bool available)
Sets the Available.
available The available.
References AvailableChanged, IsAvailable.
void Weapon.TestAddLevel()
Executes the TestAddLevel operation.
References AddLevel.
void Weapon.DebugWeaponStats()
Executes the DebugWeaponStats operation.
References weaponData.