TransitionManager
TransitionManager TransitionManager.Instance
Referenced by QuestGiver.Interact, Menu.QuitGame.
void TransitionManager.Awake()
void TransitionManager.TransitPlayerToNextLevel()
Executes the TransitPlayerToNextLevel operation.
References TransitPlayerToLevel.
Referenced by QuestGiver.Interact.
void TransitionManager.TransitPlayerToLevel(int i)
Executes the TransitPlayerToLevel operation.
i The i.
References QuestManager.activeQuests, QuestManager.CancelQuest, QuestManager.completedQuests, EnemyPoolList.EnquePools, GameStateManager.Instance, QuestManager.Instance, EnemyPoolList.instance, GameStateManager.IsPaused, GameStateManager.ResumeGame.
Referenced by Menu.QuitGame, TransitPlayerToNextLevel.