GameMenuController
GameMenuController GameMenuController.Instance
Referenced by Chest.Interact, QuestGiver.Interact, Chest.MakeNonReady, QuestGiver.MakeNonReady, Chest.MakeReady, QuestGiver.MakeReady.
GameObject GameMenuController._mutationRewardMenu
Referenced by GiveMutationReward.
GameObject GameMenuController._mutationChestInfoPanel
Referenced by RemoveFromSceneWarningOnMutatiOnChest, ShowWarningOnMutatiOnChest.
GameObject GameMenuController._mutationChestCostPanel
Referenced by RemoveFromSceneCostOnMutatiOnChest, ShowCostOnMutatiOnChest.
GameObject GameMenuController._itemRewardMenu
Referenced by GivePlayerItemReward.
GameObject GameMenuController._questInfoPanel
Referenced by RemoveFromSceneQuestInfo, ShowQuestInfo.
GameObject GameMenuController._questRewardInfoPanel
Referenced by RemoveFromSceneQuestRewardInfo, ShowQuestRewardInfo.
void GameMenuController.Awake()
void GameMenuController.GivePlayerItemReward()
Executes the GivePlayerItemReward operation.
References _itemRewardMenu.
Referenced by QuestGiver.Interact.
void GameMenuController.GiveMutationReward()
Executes the GiveMutationReward operation.
References _mutationRewardMenu.
Referenced by Chest.Interact.
void GameMenuController.RemoveFromSceneCostOnMutatiOnChest()
Removes FromSceneCostOnMutatiOnChest.
References _mutationChestCostPanel.
Referenced by Chest.Interact, Chest.MakeNonReady.
void GameMenuController.ShowCostOnMutatiOnChest(Transform _chestTransform, string moneyRequired)
Shows UI element.
_chestTransform The _chestTransform. moneyRequired The moneyRequired.
References _mutationChestCostPanel.
Referenced by Chest.Interact, Chest.MakeReady.
void GameMenuController.RemoveFromSceneWarningOnMutatiOnChest()
Removes FromSceneWarningOnMutatiOnChest.
References _mutationChestInfoPanel.
Referenced by Chest.Interact.
void GameMenuController.ShowWarningOnMutatiOnChest(Transform _chestTransform)
Shows UI element.
_chestTransform The _chestTransform.
References _mutationChestInfoPanel.
Referenced by Chest.Interact.
void GameMenuController.RemoveFromSceneQuestInfo()
Removes FromSceneQuestInfo.
References _questInfoPanel.
Referenced by QuestGiver.MakeNonReady.
void GameMenuController.ShowQuestInfo(Transform _chestTransform, string Text)
Shows UI element.
_chestTransform The _chestTransform. Text The Text.
References _questInfoPanel.
Referenced by QuestGiver.MakeReady.
void GameMenuController.RemoveFromSceneQuestRewardInfo()
Removes FromSceneQuestRewardInfo.
References _questRewardInfoPanel.
Referenced by QuestGiver.MakeNonReady.
void GameMenuController.ShowQuestRewardInfo(Transform _chestTransform, string Text)
Shows UI element.
_chestTransform The _chestTransform. Text The Text.
References _questRewardInfoPanel.
Referenced by QuestGiver.MakeReady.