EnemyPool
GameObject EnemyPool.enemyPrefab
Queue<GameObject> EnemyPool.enemyPool
void EnemyPool.EnquePool()
Executes the EnquePool operation.
References GetEnemyBackToPool.
void EnemyPool.GetEnemy(Vector3 position)
Gets the Enemy.
position The position.
Referenced by EnemySpawner.SpawnFastMeleeEnemy, EnemySpawner.SpawnSmallMeleeEnemy, EnemySpawner.SpawnSmallRangedEnemy, EnemySpawner.SpawnStrongMeleeEnemy.
void EnemyPool.GetEnemyBackToPool(GameObject enemy)
Gets the EnemyBackToPool.
enemy The enemy.
Referenced by EnquePool.