EnemySpawnManager
EnemySpawnManager EnemySpawnManager.Instance
Referenced by GameStateManager.SetPaused.
float EnemySpawnManager._spawnPatrolPeriod
float EnemySpawnManager._spawnWavePeriod
float EnemySpawnManager._difficulty
float EnemySpawnManager._periodOfGettingPoints
int EnemySpawnManager._points
float EnemySpawnManager._pointsToGain
float EnemySpawnManager._timeForPatrolPeriod
float EnemySpawnManager._timeForWavePeriod
float EnemySpawnManager._timeForGettingPoints
bool EnemySpawnManager._spawnIsActive
void EnemySpawnManager.Awake()
void EnemySpawnManager.Update()
void EnemySpawnManager.SpawnWave(int pointsToSpend)
void EnemySpawnManager.SpawnPatrol(int pointsToSpend)
async void EnemySpawnManager.SpawnSmallAmountOfEnemy(int pointsToSpend)
async void EnemySpawnManager.SpawnMediumAmountOfEnemy(int pointsToSpend)
async void EnemySpawnManager.SpawnBigAmountOfEnemy(int pointsToSpend)
bool EnemySpawnManager.TryToSpendPoints(int pointsToSpend)
Executes the TryToSpendPoints operation.
pointsToSpend The pointsToSpend. The result as bool.
Referenced by ChangeActiveEnemySpawn.
void EnemySpawnManager.GainPoints(int pointsToGain)
Referenced by ChangeActiveEnemySpawn.
void EnemySpawnManager.GainDifficulty(float gain)
Referenced by ChangeActiveEnemySpawn.
void EnemySpawnManager.ChangeActiveEnemySpawn(bool set)
References GainDifficulty, GainPoints, TryToSpendPoints.
Referenced by GameStateManager.SetPaused.