PlayerInput::PlayerActions
PlayerInput PlayerInput.PlayerActions.m_Wrapper
InputAction PlayerInput.PlayerActions.Move
Provides access to the underlying input action "Player/Move".
InputAction PlayerInput.PlayerActions.Click
Provides access to the underlying input action "Player/Click".
bool PlayerInput.PlayerActions.enabled
PlayerInput.PlayerActions.PlayerActions(@PlayerInput wrapper)
Construct a new instance of the input action map wrapper class.
References PlayerInput.PlayerInput.
Referenced by PlayerInput.PlayerActions.operator InputActionMap.
InputActionMap PlayerInput.PlayerActions.Get()
Provides access to the underlying input action map instance.
Referenced by PlayerInput.PlayerActions.Disable, PlayerInput.PlayerActions.Enable.
void PlayerInput.PlayerActions.Enable()
References PlayerInput.PlayerActions.Get.
void PlayerInput.PlayerActions.Disable()
References PlayerInput.PlayerActions.Get.
void PlayerInput.PlayerActions.AddCallbacks(IPlayerActions instance)
Adds InputAction.started, InputAction.performed and InputAction.canceled callbacks provided via on all input actions contained in this map.
instance Callback instance. If instance is null or instance have already been added this method does nothing. PlayerActions
References PlayerInput.IPlayerActions.OnClick, PlayerInput.IPlayerActions.OnMove.
Referenced by PlayerInput.PlayerActions.SetCallbacks.
void PlayerInput.PlayerActions.RemoveCallbacks(IPlayerActions instance)
Unregisters and unregisters all input action callbacks via PlayerActions.UnregisterCallbacks(IPlayerActions).
PlayerActions.UnregisterCallbacks(IPlayerActions)
void PlayerInput.PlayerActions.SetCallbacks(IPlayerActions instance)
Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via .
If instance is null, calling this method will only unregister all existing callbacks but not register any new callbacks. PlayerActions.AddCallbacks(IPlayerActions), PlayerActions.RemoveCallbacks(IPlayerActions), PlayerActions.UnregisterCallbacks(IPlayerActions)
References PlayerInput.PlayerActions.AddCallbacks.
static implicit PlayerInput.PlayerActions.operator InputActionMap(PlayerActions set)
Implicitly converts an to an instance.
References PlayerInput.PlayerActions.PlayerActions.
void PlayerInput.PlayerActions.UnregisterCallbacks(IPlayerActions instance)
Removes InputAction.started, InputAction.performed and InputAction.canceled callbacks provided via on all input actions contained in this map.
Calling this method when instance have not previously been registered has no side-effects. PlayerActions